permalink: /:categories/:title.html
url: "https://halthewise.github.io"
full_name: "Eric Miller"
first_name: "Eric"
last_name: "Miller"
blog_title: "The Project Log "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "halthewise"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
#twitter: ""
github: "halthewise"
#facebook: "mepasindu"
linkined_url: "https://www.linkedin.com/in/eric-miller-963043bb"
