# Site settings
title: Consistently Impossible
description: "The Adventures and Misadventures of Eric Miller"
url: "https://HALtheWise.github.io"




# Secondary Parameters
baseurl: ""
header-img: img/header-traces-small.png
headercolor: "#FFFFFF"
logo: /halthewise/img/favicon.png

# Tertiary Parameters
github_username:  HALtheWise
# project_repository: project-pages
disqus_shortname: halthewise
g-analytics: UA-89461006-1
# altmetric: true

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

post_assets: img/gdocs

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/header-traces-small.png"
